#local database connection configuration
#spring.datasource.url=jdbc:mysql://localhost:8889/cloud_app
#spring.datasource.username=root
#spring.datasource.password=root 

#JawsDB configuration
spring.datasource.url=${JAWSDB_URL}
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false


