#local database connection configuration
#spring.datasource.url=jdbc:mysql://localhost:8889/cloud_app
#spring.datasource.username=root
#spring.datasource.password=root 

#JawsDB configuration
spring.datasource.url=${JAWSDB_URL}
spring.datasource.username=
spring.datasource.password=

#Azure configuration
#spring.datasource.url=jdbc:mysql://cst323cloudapp.mysql.database.azure.com:3306/cloudapp?useSSL=true&requireSSL=false&serverTimezone=UTC
#spring.datasource.username=cloudappUser1@cst323cloudapp
#spring.datasource.password=passuuord1
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Amazon AWS configuration
#spring.datasource.url=jdbc:mysql://awseb-e-3jhngqwum8-stack-awsebrdsdatabase-kvorzzjez1wm.cobkyeusmfra.us-east-1.rds.amazonaws.com:3306/ebdb?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=rootroot1
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

